$(document).ready(function() {
    $("li#home").click(function() {
        $(".movies").hide()
        $(".tv-shows").hide()
        $(".review").hide()
        $("#welcome").hide()
        $("#fromovies").hide()
        $(".home").fadeIn()
    })
    $("li#movies").click(function() {
        $(".home").hide()
        $(".tv-shows").hide()
        $(".review").hide()
        $("#welcome").hide()
        $("#fromovies").hide()
        $(".movies").fadeIn()
    })
    $("li#tv").click(function() {
        $(".home").hide()
        $(".movies").hide()
        $(".review").hide()
        $("#welcome").hide()
        $("#fromovies").hide()
        $(".tv-shows").fadeIn()
    })
    $("li#review").click(function() {
        $(".home").hide()
        $(".movies").hide()
        $(".tv-shows").hide()
        $("#welcome").hide()
        $("#fromovies").hide()
        $(".review").fadeIn()
    })
  })